version: "3.8"

services:
  app:
    #Ahora ponemos el contexto de build
    build: .
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000:3000"
    #opcion para hacer un volumen solo para este servicio
    volumes:
    #Ejemplo:  acontinuacion se montara lo que hay en el direcotrio actual
    #en el directorio /usr/src del servicio
      - .:/usr/src
    #aqui, le decimos que de esa copia, omita el siguiente directorio
    #donde estan las dependencias, sino, en el siguiente  build lo sobre escribe  
      - /usr/src/node_modules 
    command: npx nodemon --legacy-watch index.js  
  db:
    image: mongo
